#!/usr/bin/env python3
"""Canonical provider selector metadata; no provider client or live mode."""
from __future__ import annotations
import argparse, json
from typing import Any

_ROWS = [
('Featured','US','browser-only','manual-only','https://featured.com/','featured'),('Qwoted','US','browser-only','manual-only','https://www.qwoted.com/','qwoted'),('Source of Sources','US','browser-only','manual-only','https://www.sourceofsources.com/','source-of-sources'),('MentionMatch','US','API-capable','permission-required','https://mentionmatch.com/api','mentionmatch'),('JournoFinder','US','official OAuth MCP','permission-required','https://mcp.journofinder.com','journofinder'),('news aktuell zimpel','Germany','authenticated dataset','permission-required','https://www.newsaktuell.de/zimpel/','news-aktuell-zimpel'),('IVW','Germany','public-web lookup','supported','https://www.ivw.de/','ivw'),('Impressum','Germany','public-web lookup','supported','https://www.gesetze-im-internet.de/ddg/__5.html','impressum'),('PR Newswire Asia','Mainland China','authenticated dataset','permission-required','https://www.prnasia.com/products/media-database/','pr-newswire-asia'),('Cision','Mainland China','authenticated dataset','permission-required','https://www.cision.com/','cision'),('ProfNet','Mainland China','browser-only','manual-only','https://www.prnewswire.com/profnet/','profnet'),('Niumedia','Mainland China','browser-only','manual-only','https://niumedia.cn/','niumedia'),('WeChat public accounts','Mainland China','browser-only','manual-only','https://weixin.qq.com/','wechat-public-accounts'),('PRONE/PRM','Japan','authenticated dataset','permission-required','https://prone.jp/prm','prone-prm'),('Foreign Press Center Japan','Japan','public-web lookup','supported','https://fpcj.jp/en/assistance/fpregcard/','foreign-press-center-japan'),('Kyodo News PR Wire','Japan','browser-only','manual-only','https://kyodonewsprwire.jp/corp/domestic/service-en/','kyodo-news-pr-wire'),('Knewin','Brazil','authenticated dataset','permission-required','https://www.knewin.com/mailing-de-imprensa/','knewin'),('Comunique-se','Brazil','browser-only','manual-only','https://www.comunique-se.com.br/','comunique-se'),('Ajor','Brazil','public-web lookup','supported','https://ajor.org.br/sete-bancos-de-fontes-gratuitos-para-jornalistas/','ajor'),('WhatsApp professional routes','Brazil','browser-only','manual-only','https://www.whatsapp.com/','whatsapp-professional-routes'),('Hunter','cross-market','API-capable','permission-required','https://hunter.io/api-documentation/v2','hunter'),('Clay','cross-market','official OAuth MCP','permission-required','https://api.clay.com/v3/mcp','clay'),('Apollo','cross-market','API-capable','permission-required','https://docs.apollo.io/reference/people-enrichment','apollo')]
_ROWS = [(n,m,c,s,u,{'news-aktuell-zimpel':'zimpel','wechat-public-accounts':'wechat','prone-prm':'prone','foreign-press-center-japan':'fpcj'}.get(g,g)) for n,m,c,s,u,g in _ROWS]
PROVIDERS: tuple[dict[str, Any], ...] = tuple(dict(name=n, market=m, **{'class': c, 'status': s, 'url': u, 'guide': g}) for n,m,c,s,u,g in _ROWS)
def inventory() -> list[dict[str, Any]]: return [dict(p) for p in PROVIDERS]
if __name__ == '__main__':
    p=argparse.ArgumentParser(description=__doc__); p.add_argument('--inventory',action='store_true'); a=p.parse_args()
    if not a.inventory: p.error('only --inventory is supported; provider clients are not implemented')
    print(json.dumps(inventory(), ensure_ascii=False, indent=2, sort_keys=True))
